apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculadora-front
  namespace: calculadora
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.calculadora.cytei.com.br
      secretName: calculadora-front-tls
  rules:
    - host: app.calculadora.cytei.com.br
      http:
        paths:
          - pathType: Prefix
            path: "/api/"
            backend:
              service:
                name: calculadora-api-service
                port:
                  number: 80
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: calculadora-front-service
                port:
                  number: 80

status:
  loadBalancer: {}
