apiVersion: v1
kind: Service
metadata:
  name: calculadora-front-service
  namespace: calculadora
spec:
  selector:
    app: calculadora-front
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
